services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env.migrations
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
