services:
  blog-api:
    image: node:20-alpine
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: sh -c "npm install && npm run start:dev"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
