services:
  blog-api:
    image: node:20-alpine
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: sh -c "npm install && npm run start:dev"
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
